# Change these first
owner: 0xpanoramix # Your GitHub organization or username, where this repository lives
repo: flashbots-boost-status # The name of this repository

sites:
  - name: Kiln
    url: https://builder-relay-kiln.flashbots.net/eth/v1/builder/status

  - name: Ropsten
    url: https://builder-relay-ropsten.flashbots.net/eth/v1/builder/status

  - name: Sepolia
    url: https://builder-relay-sepolia.flashbots.net/eth/v1/builder/status

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /flashbots-boost-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Flashbots Boost Status
  introTitle: "**Flashbots is a R&D organization working on mitigating the negative externalities of Maximal Extractable Value (MEV) on Ethereum."
  introMessage: This is a simple page showing the current status of Flashbots' relayers.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
